//node {
//   echo 'Hello World!!!'
//}
// This shows a simple build wrapper example, using the Timestamper plugin.
Random random = new Random();

node {
    // Adds timestamps to the output logged by steps inside the wrapper.
    stage('AutoTriggerGithubPull') {
        echo "Hey, look, some code has committed to SCM!!! Let's start"
	sleep random.nextInt(14) + 1;
    }

    stage('Build') {
        echo "Build from application code"
	sleep random.nextInt(19) + 1;
    }
    
    stage('Package') {
        echo "Let's package build code together in deployable format!!!"
	sleep random.nextInt(4) + 1;
    }

    stage('Code scan') {
        echo "Let's run codescan"
	sleep random.nextInt(9) + 1;
    }

    stage('Unit Testing') {
        echo "Let's run unit test"
	sleep 3
    }

    stage('freeze_package') {
        echo "Let's freeze the package"
	echo "Upload package to Artifactory/Nexus"
	sleep random.nextInt(1) + 1;
    }

    stage('deploy to Dev') {
        echo "Upload package from Artifactory/Nexus"
	sleep random.nextInt(3) + 1;
    }

    stage('Run Test Case - DEV') {
       	echo "Let's run test case for Dev"
	sleep random.nextInt(4) + 1;
    }

    stage('deploy to Staging') {
        echo "Upload package from Artifactory/Nexus"
	sleep random.nextInt(8) + 2;
    }

    stage('Run Test Case - Staging') {
       	echo "Let's run test case for Staging"
	sleep random.nextInt(4) + 1;
    }

    stage('deploy to Prod') {
        echo "Upload package from Artifactory/Nexus"
	sleep random.nextInt(13) + 2;
    }

    stage('Run Test Case - Prod') {
       	echo "Let's run Verification for Production"
	sleep random.nextInt(4) + 1;
    }

}